### ISSUE TITLE
设置完主题之后，是修改了，但是在后台杀掉app再进来还是之前的主题，这是在28版本上的问题，有解答一下为什么

### ISSUE THREAD

**Issue by qingwadaxia** [WindySha/XSkinLoader#10]

**Comment by WindySha** [comment]
有没有在应用的Application的onCreate中调用  
`SkinManger.get().loadSkin(skin_apk_path)`
是不是用的最新代码？

**Comment by qingwadaxia** [comment]
应该是用的最新代码，的确没调用 SkinManger.get().loadSkin(skin_apk_path) 但是我看内部也没有存储skin_apk_path 这个地方啊，需要用shareprefrence的方式在设置完存储一下。我说的对么？

**Comment by WindySha** [comment]
是的，需要自己存储一下设置过的apk路径  应用下次启动的时候 读出来，加载就行
