### ISSUE TITLE
首先说项目真的很棒，简单集成，功能全面。用的过程中有些问题想请教一下

### ISSUE THREAD

**Issue by gaoleicoding** [WindySha/XSkinLoader#3]
1、View也就是水平分割线和布局（如LinearLayout或
RelativeLayout）使用style，android:background必须写到xml中而不能放在style中，放入无效，是吗
2、skin:enable="true" 这个属性不能放到style中吗
3、skin:enable在代码中飘红

**Comment by WindySha** [comment]
1. 需要自己仿照TextViewTextColorStyleParser写一个解析类ViewBackgroundStyleParser，并添加注册即可：StyleParserFactory.addStyleParser(new ViewBackgroundStyleParser());，假如急需的话，我有空可以给你加上
2. 暂时不能支持放到style中，如果自己有这个需求，可以加相关支持
3. 需要在xml上加命名空间：xmlns:skin="http://schemas.android.com/android/skin"

**Comment by WindySha** [comment]
这个提醒可以忽略，不影响使用。
你也可以在build.gradle中增加：
```
lintOptions {
        abortOnError false
    }
```
这样，就没有提醒了
